/**
 * DOM cache — validated, single query, frozen
 * @module ui/dom
 */
function $id(id) {
  const el = document.getElementById(id);
  if (!el) console.warn(`[DOM] missing #${id}`);
  return el;
}

export const DOM = Object.freeze({
  toggleBtn: $id('toggleBtn'),
  playIcon: $id('playIcon'),
  stopIcon: $id('stopIcon'),
  btnText: $id('btnText'),
  clearBtn: $id('clearBtn'),
  statusText: $id('statusText'),
  logoDot: document.querySelector('.logo-dot'),
  audioSourceSelect: $id('audioSourceSelect'),
  englishLog: $id('englishLog'),
  englishInterim: $id('englishInterim'),
  enPlaceholder: $id('enPlaceholder'),
  vietnameseLog: $id('vietnameseLog'),
  vietnameseInterim: $id('vietnameseInterim'),
  viPlaceholder: $id('viPlaceholder'),
  transcriptFeed: $id('transcriptFeed'),
  combinedPlaceholder: $id('combinedPlaceholder'),
  transcriptContent: $id('transcriptContent'),
  combinedWordCount: $id('combinedWordCount'),
  interimBlock: $id('interimBlock'),
  copyAllBtn: $id('copyAllBtn'),
  suggestToggle: $id('suggestToggle'),
  suggestionDock: $id('suggestionDock'),
  qCountBadge: $id('qCountBadge'),
  questionPills: $id('questionPills'),
  suggestionBody: $id('suggestionBody'),
  suggestEmpty: $id('suggestEmpty'),
  clearSuggestionsBtn: $id('clearSuggestionsBtn'),
  copyEnBtn: $id('copyEnBtn'),
  copyViBtn: $id('copyViBtn'),
  permissionOverlay: $id('permissionOverlay'),
  grantPermissionBtn: $id('grantPermissionBtn'),
  liveBadge: $id('liveBadge'),
  enWordCount: $id('enWordCount'),
  viWordCount: $id('viWordCount'),
  toastContainer: $id('toastContainer'),
  tabLive: $id('tabLive'),
  tabSummary: $id('tabSummary'),
  liveTabContent: $id('liveTabContent'),
  summaryTabContent: $id('summaryTabContent'),
  settingsBtn: $id('settingsBtn'),
  settingsOverlay: $id('settingsOverlay'),
  closeSettingsBtn: $id('closeSettingsBtn'),
  baseUrlInput: $id('baseUrlInput'),
  apiKeyInput: $id('apiKeyInput'),
  toggleApiKeyVisibilityBtn: $id('toggleApiKeyVisibilityBtn'),
  modelInput: $id('modelInput'),
  geminiModelSelect: $id('geminiModelSelect'),
  saveSettingsBtn: $id('saveSettingsBtn'),
  apiWarningCard: $id('apiWarningCard'),
  configNowBtn: $id('configNowBtn'),
  summaryLangSelect: $id('summaryLang'),
  summaryDetailSelect: $id('summaryDetail'),
  generateSummaryBtn: $id('generateSummaryBtn'),
  copySummaryBtn: $id('copySummaryBtn'),
  summaryPlaceholder: $id('summaryPlaceholder'),
  summaryMarkdown: $id('summaryMarkdown'),
  summaryLoading: $id('summaryLoading'),
  summaryContent: $id('summaryContent'),
  contextPromptInput: $id('contextPromptInput'),
  contextPromptBadge: $id('contextPromptBadge'),
  clearContextPromptBtn: $id('clearContextPromptBtn'),
});
