export const CONFIG = Object.freeze({
  // tuned after evaluation: slightly longer silence to reduce premature cuts, debounce faster for responsiveness
  SILENCE_THRESHOLD: 900,
  MAX_INTERIM_LENGTH: 80,
  MAX_DOM_UTTERANCES: 120,
  INTERIM_DEBOUNCE_MS: 420,
  TRANSLATION_CACHE_MAX: 500,
  MAX_CONCURRENT_TRANSLATE: 3,
  COMPRESS_INTERVAL_MS: 10 * 60 * 1000,
  COMPRESS_RECENT_KEEP: 10,
  COMPRESS_MAX_CHARS: 6000,
  // Memory meter budget (display + inspector OFF-mode budget): 30000 chars ≈ 7500 tokens ≈ 1.5-2h speech.
  MEMORY_BUDGET: 30000,
  // Suggest prompt budgets (tail of memory, per-call cost/latency guard):
  // fast path (default) keeps latency ~2-3s; quality path for richer context.
  SUGGEST_CTX_FAST: 8000,
  SUGGEST_CTX_QUALITY: 12000,
  SUGGEST_RECENT_FAST: 3000,
  SUGGEST_RECENT_QUALITY: 4000,
  SPEAKER_VAD_RMS_THRESH: 0.012,
  SPEAKER_MIN_PAUSE_MS: 350,
  SPEAKER_MIN_SPEECH_MS: 600,
  SPEAKER_CENTROID_DIFF: 320,
  TRANSLATE_TIMEOUT_MS: 8500,
  TRANSLATE_FALLBACK_ENABLED: true,
  TRANSLATE_FALLBACK_TIMEOUT_MS: 8000,
  TRANSLATE_AI_FALLBACK_TIMEOUT_MS: 15000,
  MYMEMORY_MAX_CHARS: 450,
  SUGGEST_MAX_RETRIES: 2,
  SUGGEST_CACHE_TTL_MS: 10 * 60 * 1000,
  SUGGEST_STREAM_ENABLED: true,
  SUGGEST_FAST_MAX_TOKENS: 384,
  SUGGEST_QUALITY_MAX_TOKENS: 700,
  STORAGE_KEYS: Object.freeze({
    suggestEnabled: 'suggestEnabled',
    compressEnabled: 'compressEnabled',
    compressedSummary: 'compressedSummary',
    lastCompressedIdx: 'lastCompressedIdx',
    suggestContextPrompt: 'suggestContextPrompt',
    providerBaseUrl: 'providerBaseUrl',
    providerApiKey: 'providerApiKey',
    providerModel: 'providerModel',
  }),
});
